# Generated by Django 3.2.15 on 2022-08-09 04:26

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
